### ISSUE TITLE
Hacker's Gateブース参加 in ぺちこん

### ISSUE THREAD

**Issue by cocoeyes02** [hacker-s-gate/events#11]
## 何故やりたいか
* Hacker's Gate のブランディング
* エンジニア組織としての WG の知名度向上
* 単純に僕がワクワクする

## 目指すべきゴールは何か
* ぺちこんへのブース参加

## ぺちこんである利点
* 大規模イベントの企業ブース参加のナレッジ獲得
* 老若男女問わず幅広い層への WG・Hacker's Gate 知名度向上
    * [去年のぺちこんでは、サポーターズがこんな試みをしていました](https://supporterz.jp/events/detail/6469)
* 参加人数が多いので、スポンサー費用に対しての費用対効果が良い

## 決まっていないこと・わかっていないこと例
* 費用対効果に見合っているのか
* 中長期的にどんなメリットがあるのか
* ノベルティとか必要か などなど…
    * 関連：[org / ノベルティ作成の検討 #5](https://github.com/hacker-s-gate/org/issues/5)

**Comment by IkezoeMakoto** [comment]
わくわくいいですね！
