### ISSUE TITLE
2019年06月開催 LT 会／connpass ページ作成

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#17]
## connpass ページ作成
 - 枠ごとの参加人数上限
 - - 一般参加枠
 - - - 20人（必要に応じて増やす）
 - - LT枠
 - - - 5人
 - - - 5人 * 8分 = 40分/120分
 - - 運営枠
 - - - 8人（増えたら都度更新）
 - イベント名
 - - 開発のこだわりLT会〜Super Developer Experience〜
 - イベント概要
 - - ソフトウェア・ハードウェア問わず開発のこだわりを発表してもらう
 - タイムスケジュール
 - - 19:00会場
 - - 19:30開始
 - - 19:30-19:50説明
 - - 19:55LT
 - - 19:05LT
 - - 20:15LT
 - - 20:25LT
 - - 20:35LT
 - - 20:40懇親会移行
 - - 21:20閉会
 - - 21:30完全解散
 - アイキャッチ
 - - @8845musign done

**Comment by IkezoeMakoto** [comment]
これ期日いつくらいまででしたっけ？

**Comment by okashoi** [comment]
> これ期日いつくらいまででしたっけ？

MUST が 5/24（金）

ただ早ければ早いほど良い

**Comment by okashoi** [comment]
そういえば、公開されたので close しますねー
