### ISSUE TITLE
2019年06月開催 LT 会／宣伝

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#18]
#9 

- [ ] 宣伝（全員で）
    - [ ] SNS・知人に直接・所属コミュニティ等
        - [x] 開催直後
        - [ ] 定期
        - [ ] 直前
    - [ ] 社内（拡散のお願い）
        - [ ] slack
        - [ ] 朝礼

**Comment by IkezoeMakoto** [comment]
これはconnpassページできたらみんなで協力してやってもらうイメージかな？

**Comment by IkezoeMakoto** [comment]
これはどの状態になったら完了になる？（できる？）

**Comment by okashoi** [comment]
申し込みがほぼ上限まで達するか、当日を迎えるかのどちらかかな

（「やること」として洗い出しただけだから、あんまり完了については考えずに作ってしまった）

**Comment by IkezoeMakoto** [comment]
できればどんどんタスクこなしたらクローズできるようにしたい気持ちがある。

チケットが残り続けると、何残ってるんだっけ？が可視化しづらいので

**Comment by IkezoeMakoto** [comment]
## 現状
* 参加者: 15/20
* 発表者: 3/5

**Comment by IkezoeMakoto** [comment]
## 現状
- 参加者: 13/20
- 発表者: 3/5

**Comment by IkezoeMakoto** [comment]
# 現状
* 参加者: 18/20
* 発表者: 5/5
