### ISSUE TITLE
2019年06月開催 LT 会／利用備品の申請

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#19]
#9 

社内手続きのため、詳細は会社の Conluence に記載

**Comment by IkezoeMakoto** [comment]
担当者に進捗だけ書いてもらいたいなー

利用備品なので納期は前日までに使える状態になってればいいかな

**Comment by cocoeyes02** [comment]
> 担当者に進捗だけ書いてもらいたいなー

一旦 @miyanishi-yuki さんからいつもの稟議フォーマットはいただきました！
それ以外の進捗はまだない状態ですー

**Comment by cocoeyes02** [comment]
こちらも申請出しました！

**Comment by cocoeyes02** [comment]
こちら申請の詳細は、会社の Conluence に記載したので close します
