### ISSUE TITLE
パネルディスカッション準備

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#2]
あとで読む

- [x] https://www.publickey1.jp/blog/12/post_211.html
- [x] https://www.publickey1.jp/blog/12/post_212.html
- [x] https://katsuki.hatenablog.com/entry/2018/09/05/073855
- [x] https://yaplog.jp/ultgear_lasrun/archive/641
- [x] https://mirai.doda.jp/theme/publishing/panel-discussion/

やること

- [x] 事前打ち合わせ
    - [x] 日程打診
    - [x] 日程決定
    - [x] 準備
        - [x] 質問洗い出し
        - [x] アジェンダ準備（連絡事項と決めること）
        - [x] パネラーどうしの対比（パネラーについて調べる）
    - [x] 議事録・メモ共有
- [ ] 進行事前準備
    - [x] 質問の優先度付け
    - [x] 流れの確認
    - [ ] 当日に twitter を確認する方法
    - [x] 当日用アジェンダ（パネラーの会社名／氏名を記載）、パネラー＋モデレータの人数より多めに
    - [ ] 残り時間を表示

**Comment by okashoi** [comment]
聴いた

https://ajito.fm/40/

* テンポ大事
* https://www.publickey1.jp/blog/17/twitter4jgitbucketasakusa_frameworkpower-assert.html
* 完全アドリブはリスクが高すぎる
* 仕込みをしすぎるとライブ感がでない
    * 聴き手にも仕込み感が伝わってしまう
* 事前打ち合わせ
    * 会議室を取って実際の尺の3倍くらい喋る
        * 「特定のパネラーしか喋れない内容」などが出てくる
        * それら洗い出して、優先度をつけていく
* パネルディスカッション専用のハッシュタグ→それだけを投影する
    * 質問だけじゃなくて空気感を把握できる
* 聴衆の属性を把握する質問
* 専門用語など、モデレータが素人として聞く
* パネルディスカッションはなるべく平等主義を排する
    * 割り込む／質問を飛ばす／全員に回答を聞かないなど
        * それができる関係性を作っておく
        * そういう進め方であることの合意を取る
    * **敬意はもちつつ遠慮はしないようにする**

**Comment by okashoi** [comment]
> 日程打診

調整さんを使った

**Comment by okashoi** [comment]
> 質問洗い出し

Google スプレッドシートに転記
「誰に振れそうな質問か」「モデレータ備考欄」（面白そう、発表内で出てきそう、とか）を追記してからパネラーに事前共有した

**Comment by okashoi** [comment]
> 事前打ち合わせ

facebook メッセンジャーのビデオ通話機能を利用

議事録は Google ドキュメント を利用

**Comment by IkezoeMakoto** [comment]
完了
