### ISSUE TITLE
2019年06月開催 LT 会／稟議&事前申請

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#20]
#9 

社内手続きのため、詳細は会社の Conluence に記載

- [x] 稟議
- [x] 事前申請

**Comment by IkezoeMakoto** [comment]
担当者に進捗いれてもらいたい

プロジェクトで管理してるからそっちでも可

**Comment by cocoeyes02** [comment]
一旦 @miyanishi-yuki さんからいつもの稟議フォーマットはいただきました！
それ以外の進捗はまだない状態です。

要：いつもどのぐらいのスケジュール感で動いているか確認

**Comment by IkezoeMakoto** [comment]
稟議はなるはやですね！

**Comment by cocoeyes02** [comment]
できれば今週中、遅くとも月曜までに申請出せるよう動きます〜

**Comment by cocoeyes02** [comment]
稟議申請出しました〜！

**Comment by cocoeyes02** [comment]
稟議申請通りました！
現在、事前申請中です！

**Comment by IkezoeMakoto** [comment]
:eyes:

**Comment by cocoeyes02** [comment]
こちら承認待ちの段階です〜
来週半ばになっても動きがなかったら、リマインドしてみようかと思います！

**Comment by cocoeyes02** [comment]
事前申請通りました！イベント前に申請する系ものは全て完了したので close します！
