### ISSUE TITLE
2019年06月開催 LT 会／飲食物の手配

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#21]
#9

**Comment by IkezoeMakoto** [comment]
想定参加人数に合わせて飲み物どれくらい、食べ物どれくらいの議論をしたほうが良さそう

**Comment by okashoi** [comment]
> 想定参加人数に合わせて飲み物どれくらい、食べ物どれくらいの議論をしたほうが良さそう

過去の開催実績を参考にできるので、あんまり議論する必要はなさそう

**Comment by cocoeyes02** [comment]
メモ：念の為稟議申請が通ってから申請する

**Comment by cocoeyes02** [comment]
こちらケータリング業者模索中です。
いつぐらいまでに申請完了した方が良いだろう…遅くとも開催1週間前まで？

**Comment by IkezoeMakoto** [comment]
これそろそろ動かないとまずそう

以前使ってたケータリングとかはどう？

**Comment by cocoeyes02** [comment]
ケータリング業者を紹介いただいたため、予算等を伝えた上で現在注文する方向に話を進めております！

**Comment by cocoeyes02** [comment]
ケータリングの注文をしました！
以下が注意点になります！

* 料理が決まったらまた連絡するね
* 人数変更ある場合は、2日前までに連絡してね
* お料理お渡し後撤退するので、使い終わった容器等は自分で処分してね

**Comment by cocoeyes02** [comment]
あとは飲み物も今週中に頼んじゃおうかなと思います！

**Comment by cocoeyes02** [comment]
飲み物も頼みました！
ビールは1ケース社内にあったので、ビール以外のお酒とソフトドリンクを注文しました！
![スクリーンショット 2019-06-17 12 53 43](https://user-images.githubusercontent.com/21007314/59577507-f8b1b700-90fe-11e9-95ee-a1d629f86e2c.png)

**Comment by cocoeyes02** [comment]
ちなみにケータリングのメニューはこんな感じになりそうです！
```
・ミラノ産プロシュート
・カプレーゼ ピンチョス
・スモーク鴨とスモークチーズ バルサミコソース
・グリルチキン香草焼き
```

**Comment by cocoeyes02** [comment]
手配自体は完了して受け取るだけなのでこの issue は close する
