### ISSUE TITLE
2019年06月開催 LT 会／開会のスライド準備

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#22]
#9 

司会進行役が担当

過去の資料を使い回すのがよさそう

## 概要

- タイムテーブル
- 会の趣旨
- 乾杯
- 司会進行自己紹介
- 会社紹介
- Hacker's GATE 紹介
- 会場案内
    - お手洗い
    - 非常口
    - 執務エリアは進入禁止
- 会場諸注意
    - 喫煙所はない（閉まっている）
    - 20:00 以降一時外出する際は WG 社員に声かけて
    - 後日ブログアップするので写真 NG の人は言って

**Comment by IkezoeMakoto** [comment]
このチケットってスライドの準備ができてることがゴール？

だとすると @rikipedia-5r  が今担当者で

>司会進行役が担当

て書いてあるの考えると司会進行＝ @rikipedia-5r になるけどその認識であってますか？

**Comment by okashoi** [comment]
> このチケットってスライドの準備ができてることがゴール？

そのつもりでした！

> 司会進行＝ @rikipedia-5r になるけどその認識であってますか？

そこは認識の齟齬が起きているかも？要確認

**Comment by IkezoeMakoto** [comment]
司会の担当決まったっぽいけど、このチームにいないからアサインできない、、

あとこのタスクのことも伝わってるんだろうか。。？
