### ISSUE TITLE
2019年06月開催 LT 会／参加者アンケート準備

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#23]
#9 

- [ ] アンケートをとる目的のすり合わせ
- [ ] 項目ぎめ
- [ ] 作成
- [ ] QR コード生成
- [ ] 配布用に QR コード印刷
- [ ] 動作確認
    - [ ] ブラウザのシークレットモードで確認する

## 注意点

* Google フォーム を使う場合 Hacker's GATE の Google アカウントでやるとよい
* 個人情報は必要ない限り取らない
    * 取る場合はその取り扱いについて法務に確認

**Comment by IkezoeMakoto** [comment]
優先度は高くない（今すぐ必要なわけではない）が、クロージングの資料作るときくらいまでにはある程度作っておきたいね

そもそも何のためにアンケート取るのか、の議論からしないと項目決められなさそう

**Comment by cocoeyes02** [comment]
まずは項目を決めるところからですね
適当に叩きの項目作って、それに対して意見・追加の提案・文句言った方が良さそう

**Comment by cocoeyes02** [comment]
> そもそも何のためにアンケート取るのか、の議論からしないと項目決められなさそう

わかる

**Comment by cocoeyes02** [comment]
メモ：
* 割と稟議系のタスクが多く、自分がアサインされているタスクが他にいくつかある
* まだタスクにアサインされていない人が多い

ので、このタスクを別の人にアサインしないか @okashoi さんに相談する

**Comment by okashoi** [comment]
チェックリストに

> アンケートをとる目的のすり合わせ

を追加した

**Comment by cocoeyes02** [comment]
> アンケートをとる目的のすり合わせ

これ月曜日に話し合いたい

**Comment by IkezoeMakoto** [comment]
👀

**Comment by okashoi** [comment]
> これ月曜日に話し合いたい

この話出来てなかった気がする（記憶にない）

**Comment by okashoi** [comment]
できた

https://docs.google.com/forms/d/e/1FAIpQLSfoKm0vrAZEvkQFO8dqhfotKVuKWlUkrBY4WepQebCD2-7Irg/viewform
