### ISSUE TITLE
2019年06月開催 LT 会／配信準備

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#24]
#9 

このあたりまだ知見が無いので、チェックリスト自体を作りながらやっていく

- [ ] そもそもやるのか？
- [ ] 機材準備
- [ ] 当日のフロー整備

**Comment by IkezoeMakoto** [comment]
これいつまでに検討しましょう？

（社内イベントとかでお試しやるとか言って全然やってなかったから、一旦そこからでもいい気がしてます）

**Comment by 8845musign** [comment]
これ一回社内LTで知見を固めたいです。
前回の機材だと問題があった＆石川さんの個人機材に頼る形になってたので

**Comment by IkezoeMakoto** [comment]
承知です。
ネクストアクションとしては次回の社内Hacker'sGATEあたりでやってみるという感じですかね？

機材の準備とかはどうしましょうかね？

**Comment by stoneriverpower** [comment]
上にもありますけど、社内LTで確かめて、手順なりを整理してから、社外向けにやる方がいい気がします。

前回スマフォのカメラで３０分以上回せなかったので、そういうのを調査してみるのはいいかもしれません。

**Comment by okashoi** [comment]
社内で知見を得てから、ということで今回はクローズしますね

**Comment by okashoi** [comment]
社内で検証して知見を貯める、というのは別途 issue たてます
