### ISSUE TITLE
2019年06月開催 LT 会／当日の役割分担決め

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#25]
* 音楽流す人
    * @Sorarinu 
* 司会進行（スライド作成込）
    * @Dash_kojima
* タイムキーパー
    * @miyanishi-yuki 
* 受付（2 人）
    * @cureseven
    * @IkezoeMakoto 
* 会場設営の陣頭指揮
    * @ryoryotaro 
* 片付け
    * 全員
* SNS 実況
   * @rikipedia-5r 
* カメラ
   * hayashi 
* 20:00 以降到着／離脱の人の案内
    * @cureseven
    * @IkezoeMakoto

**Comment by IkezoeMakoto** [comment]
受付やりたいです

**Comment by IkezoeMakoto** [comment]
>20:00 以降到着／離脱の人の案内
>@rikipedia-5r

SNS 実況やりながら、途中到着離脱者の案内は難しいのでは？（途中で抜けないといけなくなるので）

DMの監視までにして、迎えに行く人は別の人のほうが良さそう

**Comment by IkezoeMakoto** [comment]
役割分担早めにやったほうが良さそう。(開催まで2週間ちょっと)

特に司会進行

**Comment by IkezoeMakoto** [comment]
これは完了したっぽい？

**Comment by rikipedia-5r** [comment]
完了したので流します〜

**Comment by IkezoeMakoto** [comment]
> 完了したので流します〜

クローズできていないよ〜（クローズする）
