### ISSUE TITLE
2019年06月開催 LT 会／当日の段取りを事前確認

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#26]
#9 

当日の段取りについては別途テンプレを作成

**Comment by okashoi** [comment]
> 別途テンプレ

活用したい

https://github.com/oystersjp/neta-note/issues/52#issuecomment-490858098

**Comment by IkezoeMakoto** [comment]
一週間前までにあれば問題なさそう

**Comment by okashoi** [comment]
> 一週間前までにあれば問題なさそう

なのでこいつは 2019/05/21 時点で「重要ではあるが緊急ではない」

**Comment by IkezoeMakoto** [comment]
二週間前になってきた

**Comment by okashoi** [comment]
6/13（木） にカレンダーおさえた
