### ISSUE TITLE
2019年06月開催 LT 会／テックブログに記事公開

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#33]
#9 

イベントレポート

- [ ] 執筆 & 公開（テックブログ公開のフローに準ずる）
- [ ] connpass ページの「資料」にブログ記事 URL 追加

**Comment by IkezoeMakoto** [comment]
書きたい人いたらその人優先して書かせてあげたい、もしくは司会役

**Comment by okashoi** [comment]
🎉 

https://tech.willgate.co.jp/entry/2019/06/20/183000
