### ISSUE TITLE
2019年06月開催 LT 会／connpass ページに資料を添付してもらうよう発表者に依頼

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#34]
#9 

ただし強制はしない

**Comment by IkezoeMakoto** [comment]
（当日もお願いするとして）前日通知とかで発表者宛のメッセージとかに入れると良さそう

**Comment by IkezoeMakoto** [comment]
発表者へのこの依頼はどのタイミングで誰がお願いする？

私のイメージでは司会が、最初の接続テストのときに依頼すればいいかなと思ってたけど

**Comment by IkezoeMakoto** [comment]
connpassのメッセージでお願いするらしい
