### ISSUE TITLE
2019年06月開催 LT 会／connpass ページ用画像

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#35]
> @8845musign ありがとうございます！バナー作単体で issue 切ってアサインしておきますー

_Originally posted by @okashoi in https://github.com/hacker-s-gate/events/issues/9#issuecomment-490737874_

**Comment by 8845musign** [comment]
すみません、次から自分でアサインします🙏

**Comment by okashoi** [comment]
connpass ページ自体の作成を @rikipedia-5r にアサインしたので、彼とイベントのコンセプトなどについてすり合わせながら進めていただけると！

https://github.com/hacker-s-gate/events/issues/17
