### ISSUE TITLE
受付のやることを整理する

### ISSUE THREAD

**Issue by IkezoeMakoto** [hacker-s-gate/events#40]
受付のやることを整理する

_Originally posted by @IkezoeMakoto in https://github.com/hacker-s-gate/events/issues/9#issuecomment-496839360_

**Comment by cureseven** [comment]
### 事前準備
```
- connpassページ開いておく
- connpassページ印刷したもの用意
- ぺん用意
- 看板用意
   - 看板に貼る用の紙新たに準備？
- 配布用名札の準備
```

### 受付のフロー
```
- お名前(ID)確認
- 説明
   - 名札
　　- 写真NGかどうかきく
　　- 名前を書いてお待ちください
   - 開始までどう待機するか
- 名札配布
- 暮らしやmillyのステッカー配布
   - よければどうぞって感じで？
- 発表者の接続準備
　- @ryoryotaro さん接続確認お願いします
```

### 受付が終わったら
```
- 残り人数確認
- 小澤さんのTwitter確認
- 遅れてきた人の案内
   - どこまで迎えにいく？
```

紙でチェックするなら用意するもの
```
- connpassページ印刷したもの
- ぺん
```

**Comment by cureseven** [comment]
@okashoi こだわりLT会用の看板に貼るための紙を作りたいのでテンプレありましたらください

**Comment by cureseven** [comment]
@ryoryotaro 
> - 発表者の接続準備
>　- @ryoryotaro さん接続確認お願いします

**Comment by IkezoeMakoto** [comment]
>写真NGかどうかきく

写真NGなら名札の色どっちか、決めておいてカメラの人と連携しておかないと行けないね

**Comment by okashoi** [comment]
@cureseven 

看板のテンプレは社の slack の方に貼りましたー

あと、受付の大事な目的のひとつに「無関係者がオフィスに入って来ないように注意する」があるので、それが明文化できてるとよさげと思った

（具体的な行為としては上記のフローが守られてれば問題なさそう。つまり、受付を通らずに人が入ってくるってことがなければ :ok:）
