### ISSUE TITLE
2019年06月開催 LT 会／ふりかえり実施

### ISSUE THREAD

**Issue by okashoi** [hacker-s-gate/events#48]
#9

**Comment by okashoi** [comment]
全員を一箇所に集めてやると、人が多すぎて収集つかなくなりそう感

**Comment by IkezoeMakoto** [comment]
振り返りページ作って書いてもらって、その上で貴重な意見とかはピックアップ出来るように振り返り形式変えてもいいかもね

**Comment by okashoi** [comment]
いつまでも open にはしてられないので close します🙇

今回、振り返りはうまく進められなかった（結局どうするか決めないまま置いてしまった、結果薄い振り返りしか出来なかった）ので
次回イベント開催のときには振り返りの進行について開催前に決着を付けておく。これを issue として切っておきます。
