### ISSUE TITLE
イベント開催時に必要な申請と手順をまとめておく

### ISSUE THREAD

**Issue by cocoeyes02** [hacker-s-gate/events#49]
社内手続きの内容なので、社内の Confluence でまとめる

**Comment by okashoi** [comment]
#9 やった際の申請系はこの辺

* #19 
* #20 
* #31

**Comment by okashoi** [comment]
@cocoeyes02 もし、社の Confluence にまとめてあったら close しちゃってほしい（急ぎじゃないよ）
