### ISSUE TITLE
ノベルティ作成の検討

### ISSUE THREAD

**Issue by IkezoeMakoto** [hacker-s-gate/events#7]
@cocoeyes02 がやりたいらしい

**Comment by IkezoeMakoto** [comment]
やるとしたらどこで予算持つんだろうか、、

**Comment by cocoeyes02** [comment]
ちなみにノベルティが欲しい目的は、主にHackersGATE のブランディングの一環ですね。

あとは WG の認知拡大、向上にも繋がるのかな

**Comment by mism-mism** [comment]
ステッカーだと個性がない気がしているので同じくらいの値段で良さげなの作りたい

候補だけ書かせてください
メモ帳
キーボードキャップ（Gマーク）
クリアファイル
缶バッチ

**Comment by mism-mism** [comment]
特にキーボードキャップがおすすめ

**Comment by cocoeyes02** [comment]
今更ですが、これ org に書くべきな気がしてきました

**Comment by mism-mism** [comment]
cookpadのカンファレンスでは調味料の袋の口を止めるやつ貰って活躍している

**Comment by cocoeyes02** [comment]
もしやるなら [Hacker's Gate のロゴ](https://github.com/hacker-s-gate/org/issues/2) を先に作るか、あるいは一緒に作るかの方が都合が良いですね

**Comment by cocoeyes02** [comment]
https://dev.classmethod.jp/marketing/novelty-conference/
https://togetter.com/li/1309903?page=2
+ここ直近で 仕事の一環でノベルティ作った社内 PRJ のメンバーにヒアリングしてきた

何と無くイメージは掴めた気がする

**Comment by cocoeyes02** [comment]
org に 転載したのでこちらの issue は閉じますね
